### ISSUE TITLE
Item/Drying Rack Lighting (1.9, 2.3.0)

### ISSUE THREAD

**Issue by LovelyFlare** [SlimeKnights/TinkersConstruct#2103]
Drying Racks have improper lighting.
![2016-05-20_23 58 06](https://cloud.githubusercontent.com/assets/14182009/15446251/b5525f64-1ee7-11e6-9279-c6220f1e1fd3.png)
![2016-05-20_23 58 16](https://cloud.githubusercontent.com/assets/14182009/15446252/b552cd0a-1ee7-11e6-9bb2-da6636f6dc10.png)
![2016-05-21_00 04 28](https://cloud.githubusercontent.com/assets/14182009/15446254/b55610fa-1ee7-11e6-9fb0-9335a538814d.png)
![2016-05-21_00 04 39](https://cloud.githubusercontent.com/assets/14182009/15446253/b55437da-1ee7-11e6-8796-b93c8624af50.png)

**Comment by bonii-xx** [comment]
I think that has been fixed since a while

**Comment by LovelyFlare** [comment]
Still happens in 2.3.1.
![2016-05-27_20 18 09](https://cloud.githubusercontent.com/assets/14182009/15623882/dbaa34be-2448-11e6-980f-ff73d661a23a.png)
![2016-05-27_20 18 11](https://cloud.githubusercontent.com/assets/14182009/15623883/dbac2026-2448-11e6-945e-b1939608207e.png)

**Comment by bonii-xx** [comment]
I don't see what's wrong?
