### ISSUE TITLE
crash while making a bloodmagic dagger

### ISSUE THREAD

**Issue by MagieMalone** [SlimeKnights/TinkersConstruct#2118]
http://pastebin.com/Juctnww8

crash of the client while making a bloodmagic dagger. Just was putting down 5 blocks of transparent light lime blocks, and then I crashed. logging on again it keeps crashing with the same error.

**Comment by bonii-xx** [comment]
Fixed in newer versions. Disable the display in the configs to log in.

**Comment by MagieMalone** [comment]
well, I've set     B:renderTableItems=false but it still crashes... or would this need to be set server side too?

**Comment by bonii-xx** [comment]
Shouldn't affect it at all, but you can try.
