### ISSUE TITLE
[1.10.2 v2.6.1] Small graphical glitch with crossbows

### ISSUE THREAD

**Issue by xTitanium** [SlimeKnights/TinkersConstruct#2641]
Recently Tinkers Construct in 1.10.2 updated to where it has the bows, however if you go into third person, and you hold a loaded crossbow, it appears that the crossbow is literally in your face. I have a comparison of crossbows in 1.7.10 and 1.10.2

The crossbow in 1.7.10 appears normal while you are in third person
http://imgur.com/jA6DAmn
The crossbow in 1.10.2 appears that it is in your face
http://imgur.com/qqNZklf

**Comment by Joshwoo70** [comment]
![2016-12-10_14 53 13](https://cloud.githubusercontent.com/assets/7894419/21071840/e7384baa-bee8-11e6-916b-85b7e3b3f51e.png)
same. graphical isses.

**Comment by VallenFrostweaver** [comment]
To be more clear and support this glitch, just holding a crossbow: it appears you are holding a limb and not the stock/handle area. When cocking the bow the animation looks decent (as it's the same as the next animation but the arms are not raised yet). When the bow is loaded it appears as shown above which is the same as when the bow is being loaded but the arms are raised.

**Comment by KnightMiner** [comment]
Yeah, there just seems to be some errors with the display tags, the pictures are rather descriptive of the problem

**Comment by bonii-xx** [comment]
It's not an error, I simply never set the third person transforms.

**Comment by Joshwoo70** [comment]
lazy boni is lazy :P

**Comment by The-Fireplace** [comment]
I can confirm that this is still an issue in 1.12.2 running TiCon 2.7.3.30.
![2017-10-07_15 44 25](https://user-images.githubusercontent.com/5914284/31311664-8bf732d0-ab76-11e7-81f1-0667192fe79f.png)

**Comment by KnightMiner** [comment]
#3265 was fixed, so closing

**Comment by spookyjuke** [comment]
Not fixed anymore. Loaded up a craft of the titans pack running 1.10.2 of which Tinker's is a part of and behold:
![javaw_N1z3u4ZtAN](https://github.com/SlimeKnights/TinkersConstruct/assets/23448033/ac99b5ad-3bbd-45f1-8ea1-2bf9b6ff0810)

Either craft of the titans is using a bad version of tinkers or the fix here https://github.com/SlimeKnights/TinkersConstruct/issues/3265 was undone.

**Comment by KnightMiner** [comment]
We fixed it on 1.12. 1.10 has been dead for long before this issue was closed, it was never a stable release.
