### ISSUE TITLE
[1.11.2] BlockTable is not abstract and does not override abstract method func_149915_a(World,int) in BlockInventory

### ISSUE THREAD

**Issue by Ristovski** [SlimeKnights/TinkersConstruct#2863]
After applying a workaround for #2862, the build continues to fail with the aforementioned error which seems to causes many more errors down the line.
`build/sources/main/java/slimeknights/tconstruct/shared/block/BlockTable.java:43: error: BlockTable is not abstract and does not override abstract method func_149915_a(World,int) in BlockInventory`
AFAIK TCon is supposed to compile fine under 1.11.2 branch, right?

Tried `gradle clean/cleanCache` with no success.

**Comment by bonii-xx** [comment]
Should work now.

**Comment by Ristovski** [comment]
I don't know what your Jenkins is doing, but it's still broken for me. 
Log: https://bpaste.net/raw/387035479e21

**Comment by bonii-xx** [comment]
Looks like your mappings are screwed.
![6a0120a85dcdae970b0128776ff992970c-pi](https://cloud.githubusercontent.com/assets/722449/25557970/3bd9d438-2d1d-11e7-8aa0-8e7b29c806d4.png)

**Comment by Ristovski** [comment]
Seems like it kept caching something even after `gradle clean/cleanCache`. I re-cloned and it seems to be resolved.
