### ISSUE TITLE
No tool parts in JEI

### ISSUE THREAD

**Issue by zKryle** [SlimeKnights/TinkersConstruct#4301]
**Issue description:**
When writing @Tinkers in Jei i cannot find any tool parts like i expected
![a](https://user-images.githubusercontent.com/81220214/113506363-b8762f80-9544-11eb-836c-5561330c8c0d.PNG)
![a](https://user-images.githubusercontent.com/81220214/113506372-c4fa8800-9544-11eb-88b6-01027f8d9f3a.PNG)

**If crashed, link to crash report (use a site such as pastebin):**

**Versions:**
* Minecraft:1.16.5
* Forge: 3.6.10
* Mantle: 1.6.79
* Tinkers Construct: 3.0.2.73

**Confirm below that this issue is not covered on the roadmap or "Whats New?"**
I confirm it's not

**Can it be reproduced with *just* Tinkers Construct? If not, list the other mods *required* to reproduce the issue.**
No, it needs at least Jei to reproduce.

**Comment by PrincessOfEvil** [comment]
Cannot reproduce with just JEI. Find the offending mod (you can split the mod list in half to find it quicker than just one by one) and edit the issue.

**Comment by zKryle** [comment]
I found out it may be a config issue, removing mods didn't help me and i fixed it by editing the "ingredient-list-mod-sort-order.ini" file in the jei folder. I took Tinker Construct and put it Under "Minecraft" in the file.

**Comment by KnightMiner** [comment]
Most likely fixed in 3.0.2.84. Seems to be a race condition between our material loading and JEI's item loading. Let me know if the fix causes any issues, as I could only test it on a fake server

**Comment by KnightMiner** [comment]
Going to assume this fixed in 3.0.2.84. If not, leave a comment here and we can look into it again

**Comment by ocram9** [comment]
This issue isn't fixed yet, not completely anyway. Somehow the JEI addon JustEnoughResources (1.16.4-0.12.0.109) is causing this. There is also a specific order you need to follow to reproduce it:

- Have a dedicated server with JEI, JustEnoughResources, Tinkers construct and Mantle, same for the client.
- Join the server and search for tinkers construct or just scroll to the right, there won't be parts.
- Leave the server and rejoin, now the parts are visible.

As far as I can tell this doesn't happen in singleplayer worlds and after rejoining a multiplayer world it's also fine.

**Comment by KnightMiner** [comment]
Are you certain JustEnoughResources is related, its not just any mod that changes the load order? If so, did you report this to them?

In any case, this is a really, really dumb syncing bug. Has to do with the order the material registry loads vs the order JEI loads. It works the second time because your client uses the list of materials from the last server it connected to

**Comment by ocram9** [comment]
Okay so after some more testing I figured out that adding JustEnoughResources doesn't show the parts or tools when you first join. However the thing I missed was the fact that removing JustEnoughResources doesn't fix it entirely, the parts do show up in JEI but the tools don't. So this bug is reproducible with just JEI.

I haven't reported this anywhere yet but as far as I can tell this only happens with Tinkers' Construct, I could report it to JEI if you want tho

**Comment by KnightMiner** [comment]
3.0.3.136 makes another pass at fixing this. If that does not solve your problem, there is probably nothing else I can do

**Comment by ocram9** [comment]
Then it's a good thing it fixed it. Just joined a server and the tools and parts show up like they should

**Comment by KnightMiner** [comment]
Ah, perfect. Was running out of ideas. Going to close this as fixed, if anyone else has this problem in the latest build or later comment to look into it again
